# Generated by Django 3.1.3 on 2021-06-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20210608_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='lesson',
        ),
    ]
