# Generated by Django 3.1.3 on 2021-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20210608_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=1.0),
        ),
    ]
